# Generated by Django 3.0 on 2019-12-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=256, unique=True)),
                ('product_price', models.IntegerField()),
                ('product_img_url', models.CharField(max_length=256, unique=True)),
            ],
        ),
    ]
